/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gado.view;

import com.model.bean.Proprietario;
import com.model.dao.ProprietarioDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class TelaPropietario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPropietario
     */
    public TelaPropietario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableProprietario.getModel();
        jTableProprietario.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }

    public void readTable(){
       DefaultTableModel modelo = (DefaultTableModel) jTableProprietario.getModel();
       modelo.setNumRows(0);
       
       ProprietarioDAO pdao = new ProprietarioDAO();
       //for (Gado g : gdao.findByPosse()){
        for (Proprietario p : pdao.FindAll()){
            modelo.addRow(new Object[]{
                p.getIdProprietario(),
                p.getNome(),
                p.getNascimento(),
                p.getSexo(),
                p.getCpf(),
                p.getCnpj(),
                p.getCidade(),
                p.getEmail(),
                p.getCelular(),
                p.getTelefone(),
                        
            });
        }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNomeProprietario = new javax.swing.JTextField();
        jButtonAtualizarProprietario = new javax.swing.JButton();
        jTextFieldNascimentoProprietario = new javax.swing.JTextField();
        jButtonSalvarProprietario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonLimparProprietario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProprietario = new javax.swing.JTable();
        jComboBoxSexoProprietario = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCpfProprietario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCnpjProprietario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCidadeProprietario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmailProprietario = new javax.swing.JTextField();
        jTextFieldCeularProprietario = new javax.swing.JTextField();
        jTextFieldTelefoneProprietario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAtualizarProprietario.setText("Atualizar");
        jButtonAtualizarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarProprietarioActionPerformed(evt);
            }
        });

        jTextFieldNascimentoProprietario.setText("dd/mm/aaaa    ");
        jTextFieldNascimentoProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNascimentoProprietarioActionPerformed(evt);
            }
        });

        jButtonSalvarProprietario.setText("Salvar");
        jButtonSalvarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarProprietarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nascimento:");

        jButtonLimparProprietario.setText("Limpar");
        jButtonLimparProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparProprietarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo:");

        jTableProprietario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Contato", "Nome", "Nascimento", "Sexo", "CPF", "CNPJ", "Cidade", "Email", "Celular", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProprietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProprietarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProprietario);

        jComboBoxSexoProprietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        jLabel7.setText("Contatos:");

        jLabel8.setText("Cadastro de comprador/vendedor:");

        jLabel1.setText("Nome:");

        jLabel9.setText("CPF:");

        jTextFieldCpfProprietario.setText("xxx.xxx.xxx-xx");

        jLabel10.setText("CNPJ:");

        jTextFieldCnpjProprietario.setText("xxx.xxx.xxx/xxxx-xx");
        jTextFieldCnpjProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCnpjProprietarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Cidade:");

        jLabel5.setText("Email:");

        jLabel6.setText("Celular:");

        jLabel11.setText("Telefone:");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxSexoProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNascimentoProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCpfProprietario)
                                    .addComponent(jTextFieldCnpjProprietario))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(11, 11, 11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCeularProprietario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldEmailProprietario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldCidadeProprietario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldTelefoneProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSalvarProprietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAtualizarProprietario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonLimparProprietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNomeProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCidadeProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNascimentoProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldEmailProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxSexoProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCeularProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldCpfProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalvarProprietario)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAtualizarProprietario)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLimparProprietario)
                            .addComponent(jTextFieldTelefoneProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldCnpjProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonSair)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNascimentoProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNascimentoProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNascimentoProprietarioActionPerformed

    private void jTextFieldCnpjProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCnpjProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCnpjProprietarioActionPerformed

    private void jButtonSalvarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarProprietarioActionPerformed
        // TODO add your handling code here:
        cadastraProprietario();
        readTable();
        limpaCampos();
    }//GEN-LAST:event_jButtonSalvarProprietarioActionPerformed

    private void jButtonAtualizarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarProprietarioActionPerformed
        // TODO add your handling code here:
        atualizaProprietario();
        readTable();
        limpaCampos();
    }//GEN-LAST:event_jButtonAtualizarProprietarioActionPerformed

    private void jButtonLimparProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparProprietarioActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_jButtonLimparProprietarioActionPerformed

    private void jTableProprietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProprietarioMouseClicked
        // TODO add your handling code here:
        Proprietario p = new Proprietario();
        if (jTableProprietario.getSelectedRow() != -1){
          //jTextFieldRacaGado.setText(jTableGado.getValueAt(jTableGado.getSelectedRow(), 1).toString());
          jTextFieldNomeProprietario.setText(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 1).toString());
          jTextFieldNascimentoProprietario.setText(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 2).toString());
          p.setSexo(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 3).toString());
          if (p.getSexo().equalsIgnoreCase("Masculino")){
              jComboBoxSexoProprietario.setSelectedIndex(0);
            }
          else{
              jComboBoxSexoProprietario.setSelectedIndex(1);
          }
          jTextFieldCpfProprietario.setText(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 4).toString());
          jTextFieldCnpjProprietario.setText(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 5).toString());
          jTextFieldCidadeProprietario.setText(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 6).toString());
          jTextFieldEmailProprietario.setText(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 7).toString());
          jTextFieldCeularProprietario.setText(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 8).toString());
          jTextFieldTelefoneProprietario.setText(jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 9).toString());
        }
    }//GEN-LAST:event_jTableProprietarioMouseClicked

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        
        //new TelaInicial().setVisible(true);
        
         this.dispose();
        
    }//GEN-LAST:event_jButtonSairActionPerformed

    
    private void cadastraProprietario(){
        Proprietario p = new Proprietario();
        ProprietarioDAO pdao = new ProprietarioDAO();
        
        p.setNome(jTextFieldNomeProprietario.getText());
        p.setNascimento(jTextFieldNascimentoProprietario.getText());
        p.setSexo(jComboBoxSexoProprietario.getSelectedItem().toString());
        p.setCpf(jTextFieldCpfProprietario.getText());
        p.setCnpj(jTextFieldCnpjProprietario.getText());
        p.setCidade(jTextFieldCidadeProprietario.getText());
        p.setEmail(jTextFieldEmailProprietario.getText());
        p.setCelular(jTextFieldCeularProprietario.getText());
        p.setTelefone(jTextFieldTelefoneProprietario.getText());
        //c.setValor(Float.parseFloat(txtValor.getText()));
        
        
        pdao.save(p);
        limpaCampos();
        
    }
    
    
    private void atualizaProprietario(){
        
        Proprietario p = new Proprietario();
        ProprietarioDAO pdao = new ProprietarioDAO();
        

        //g.setIdGado((int) jTableGado.getValueAt(jTableGado.getSelectedRow(),0));
        p.setIdProprietario((int) jTableProprietario.getValueAt(jTableProprietario.getSelectedRow(), 0));
        p.setNome(jTextFieldNomeProprietario.getText());
        p.setNascimento(jTextFieldNascimentoProprietario.getText());
        p.setSexo(jComboBoxSexoProprietario.getSelectedItem().toString());
        p.setCpf(jTextFieldCpfProprietario.getText());
        p.setCnpj(jTextFieldCnpjProprietario.getText());
        p.setCidade(jTextFieldCidadeProprietario.getText());
        p.setEmail(jTextFieldEmailProprietario.getText());
        p.setCelular(jTextFieldCeularProprietario.getText());
        p.setTelefone(jTextFieldTelefoneProprietario.getText()); 
        
        pdao.update(p);
        limpaCampos();
    }
    
    private void limpaCampos(){
        
        jTextFieldNomeProprietario.setText(null);
        jTextFieldNascimentoProprietario.setText("dd/mm/aaaa");
        jComboBoxSexoProprietario.setSelectedIndex(0);
        jTextFieldCpfProprietario.setText(null);
        jTextFieldCnpjProprietario.setText(null);
        jTextFieldCidadeProprietario.setText(null);
        jTextFieldEmailProprietario.setText(null);
        jTextFieldCeularProprietario.setText(null);
        jTextFieldTelefoneProprietario.setText(null);
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPropietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarProprietario;
    private javax.swing.JButton jButtonLimparProprietario;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvarProprietario;
    private javax.swing.JComboBox<String> jComboBoxSexoProprietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProprietario;
    private javax.swing.JTextField jTextFieldCeularProprietario;
    private javax.swing.JTextField jTextFieldCidadeProprietario;
    private javax.swing.JTextField jTextFieldCnpjProprietario;
    private javax.swing.JTextField jTextFieldCpfProprietario;
    private javax.swing.JTextField jTextFieldEmailProprietario;
    private javax.swing.JTextField jTextFieldNascimentoProprietario;
    private javax.swing.JTextField jTextFieldNomeProprietario;
    private javax.swing.JTextField jTextFieldTelefoneProprietario;
    // End of variables declaration//GEN-END:variables
}
