/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gado.view;

import com.model.bean.Gado;
import com.model.bean.Proprietario;
import com.model.bean.Transferencia;
import com.model.dao.GadoDAO;
import com.model.dao.ProprietarioDAO;
import com.model.dao.TransferenciaDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class TelaCompra extends javax.swing.JFrame {

    /**
     * Creates new form TelaCompra
     */
    public TelaCompra() {
        initComponents();
        
        ProprietarioDAO pdao = new ProprietarioDAO();
        
        for(Proprietario p: pdao.FindAll()){
            
            jComboBoxVendedor.addItem(p);
        }
        
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTableCompra.getModel();
        jTableCompra.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }
    
     public void readTable(){
         DefaultTableModel modelo = (DefaultTableModel) jTableCompra.getModel();
         modelo.setNumRows(0);
         
         //Gado g = new Gado();
         //GadoDAO gdao = new GadoDAO();
         
         //Proprietario p = new Proprietario();
         //ProprietarioDAO pdao = new ProprietarioDAO();
         
         TransferenciaDAO tdao = new TransferenciaDAO();
         for (Transferencia t : tdao.findByCompra()){
             
             //p = t.getProprietario();
             //g = t.getGado();
             
             modelo.addRow(new Object[]{
                 t.getIdTransferencia(),
                 t.getValor(),
                 //p.getIdProprietario(),  
                 t.getProprietario(),
                 //g.getIdGado(), 
                 t.getGado(),
                 t.getFormaPagamento(),
                 t.getPrazo(),
                 t.getDataTransferencia(),
                 t.getDescricao(),
             });
         }
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBoxVendedor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldValorCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxFormaPagCompra = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDataCompra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPrazoCompra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricaoCompra = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxSexoCompra = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRacaCompra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNascimentoCompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPesoCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObservacaoCompra = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButtonSalvarCompra = new javax.swing.JButton();
        jButtonCancelarCompra = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCompra = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldVendedor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Selecionar vendedor:");

        jLabel1.setText("Compra:");

        jLabel11.setText("Forma de pagamento:");

        jComboBoxFormaPagCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "Cheque" }));

        jLabel13.setText("Data:");

        jTextFieldDataCompra.setText("dd/mm/aaaa");

        jLabel12.setText("Prazo:");

        jLabel16.setText("Meses");

        jLabel14.setText("Valor:");

        jTextAreaDescricaoCompra.setColumns(20);
        jTextAreaDescricaoCompra.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricaoCompra);

        jLabel17.setText("Descrição da compra:");

        jComboBoxSexoCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Fêmea" }));

        jLabel3.setText("Raça:");

        jLabel4.setText("Nascimento:");

        jTextFieldNascimentoCompra.setText("dd/mm/aaaa    ");
        jTextFieldNascimentoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNascimentoCompraActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo:");

        jLabel6.setText("Peso:");

        jLabel7.setText("Kg");

        jTextAreaObservacaoCompra.setColumns(20);
        jTextAreaObservacaoCompra.setRows(5);
        jScrollPane2.setViewportView(jTextAreaObservacaoCompra);

        jLabel8.setText("Observação sobre o animal:");

        jButtonSalvarCompra.setText("Salvar");
        jButtonSalvarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCompraActionPerformed(evt);
            }
        });

        jButtonCancelarCompra.setText("Cancelar");
        jButtonCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCompraActionPerformed(evt);
            }
        });

        jTableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Compra", "Valor", "Vendedor", "Animal", "Forma de pagamento", "Prazo", "Data", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCompraMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCompra);

        jLabel9.setText("Compras:");

        jLabel10.setText("Vendedor:");

        jTextFieldVendedor.setEditable(false);
        jTextFieldVendedor.setBackground(new java.awt.Color(153, 153, 153));

        jLabel15.setText("R$");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxFormaPagCompra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPesoCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrazoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxSexoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNascimentoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldRacaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(199, 199, 199)
                                .addComponent(jButtonSalvarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBoxFormaPagCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrazoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldRacaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldPesoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldNascimentoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBoxSexoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelarCompra)
                            .addComponent(jButtonSalvarCompra)
                            .addComponent(jButtonSair))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNascimentoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNascimentoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNascimentoCompraActionPerformed

    private void jButtonSalvarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCompraActionPerformed
        // TODO add your handling code here:
        cadastraCompra();
        //cadastraCompra();
        readTable();
        limpaCampos();
    }//GEN-LAST:event_jButtonSalvarCompraActionPerformed

    private void jButtonCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCompraActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_jButtonCancelarCompraActionPerformed

    private void jTableCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCompraMouseClicked
        // TODO add your handling code here:
        Gado g = (Gado) jTableCompra.getValueAt(jTableCompra.getSelectedRow(),3);
        Proprietario p = (Proprietario) jTableCompra.getValueAt(jTableCompra.getSelectedRow(),2);
        Transferencia t = new Transferencia();
        
        t.setFormaPagamento(jTableCompra.getValueAt(jTableCompra.getSelectedRow(),4).toString());
        
        
        
        if (jTableCompra.getSelectedRow() != -1){
            //jTextFieldRacaGado.setText(jTableGado.getValueAt(jTableGado.getSelectedRow(), 1).toString());
            
            jTextFieldVendedor.setText(p.getNome());
            jTextFieldRacaCompra.setText(g.getRaca());
            jTextFieldNascimentoCompra.setText(g.getNascimento());
            if (g.getSexo().equalsIgnoreCase("Macho")){
                jComboBoxSexoCompra.setSelectedIndex(0);
            }
            else {
                jComboBoxSexoCompra.setSelectedIndex(1);
            }
            jTextFieldPesoCompra.setText(String.valueOf(g.getPeso()));
            jTextAreaObservacaoCompra.setText(g.getObservacao());
            jTextFieldValorCompra.setText(jTableCompra.getValueAt(jTableCompra.getSelectedRow(),1).toString());
            jTextFieldPrazoCompra.setText(jTableCompra.getValueAt(jTableCompra.getSelectedRow(),5).toString());
            jTextFieldDataCompra.setText(jTableCompra.getValueAt(jTableCompra.getSelectedRow(),6).toString());
            jTextAreaDescricaoCompra.setText(jTableCompra.getValueAt(jTableCompra.getSelectedRow(),7).toString());
            if (t.getFormaPagamento().equalsIgnoreCase("Dinheiro")){
                jComboBoxFormaPagCompra.setSelectedIndex(0);
            }
            else if (t.getFormaPagamento().equalsIgnoreCase("Cartão")){
                jComboBoxFormaPagCompra.setSelectedIndex(1);
            }
            else{
                jComboBoxFormaPagCompra.setSelectedIndex(2);
            }
        }
    }//GEN-LAST:event_jTableCompraMouseClicked

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /*private void cadastraCompra(){
        
        Transferencia t = new Transferencia();
        TransferenciaDAO tdao = new TransferenciaDAO();
        
        GadoDAO gdao = new GadoDAO();
        //Gado g = new Gado();
        for (Gado g : gdao.findByMaior()){
             t.setGado(g);
         }
        
        
        ProprietarioDAO pdao = new ProprietarioDAO();
       // Proprietario p = new Proprietario();
       for (Proprietario p : pdao.findByMaior()){
             t.setProprietario(p);
        }  
       
       
        
        t.setTipoTransferencia("Compra");
        t.setValor(Float.parseFloat(jTextFieldValorCompra.getText()));
        t.setFormaPagamento(jComboBoxFormaPagCompra.getSelectedItem().toString());
        t.setPrazo(Integer.parseInt(jTextFieldPrazoCompra.getText()));
        t.setDataTransferencia(jTextFieldDataCompra.getText());
        t.setDescricao(jTextAreaDescricaoCompra.getText());
        
        tdao.save(t);
        limpaCampos();
        
        
        
    }*/
    
    
    
    private void cadastraCompra(){
        
        Gado g = new Gado();
        GadoDAO gdao = new GadoDAO();
        
        Transferencia t = new Transferencia();
        TransferenciaDAO tdao = new TransferenciaDAO();
        
        ProprietarioDAO pdao = new ProprietarioDAO();
        Proprietario p = (Proprietario) jComboBoxVendedor.getSelectedItem();
         
        
        //cadastra gado
        g.setRaca(jTextFieldRacaCompra.getText());
        g.setNascimento(jTextFieldNascimentoCompra.getText());             
        g.setSexo(jComboBoxSexoCompra.getSelectedItem().toString());
        g.setPeso(Float.parseFloat(jTextFieldPesoCompra.getText()));
        g.setObservacao(jTextAreaObservacaoCompra.getText());
        g.setPosse(true);
        //c.setValor(Float.parseFloat(txtValor.getText()));
                
        gdao.save(g);
        //readTable();
       
        //cadastra compra
        t.setGado(g);
        t.setProprietario(p);
        t.setTipoTransferencia("Compra");
        t.setValor(Float.parseFloat(jTextFieldValorCompra.getText()));
        t.setFormaPagamento(jComboBoxFormaPagCompra.getSelectedItem().toString());
        t.setPrazo(Integer.parseInt(jTextFieldPrazoCompra.getText()));
        t.setDataTransferencia(jTextFieldDataCompra.getText());
        t.setDescricao(jTextAreaDescricaoCompra.getText());
        
        tdao.save(t);
        limpaCampos();
    }
    
    
    
    private void limpaCampos(){
        jComboBoxVendedor.setSelectedIndex(0);
        jTextFieldVendedor.setText(null);
        jTextFieldRacaCompra.setText(null);
        jTextFieldNascimentoCompra.setText(null);
        jComboBoxSexoCompra.setSelectedIndex(0);
        jTextFieldPesoCompra.setText(null);
        jTextAreaObservacaoCompra.setText(null);
        jTextFieldValorCompra.setText(null);
        jTextFieldPrazoCompra.setText(null);
        jTextFieldDataCompra.setText(null);
        jTextAreaDescricaoCompra.setText(null);
        jComboBoxFormaPagCompra.setSelectedIndex(0);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarCompra;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvarCompra;
    private javax.swing.JComboBox<String> jComboBoxFormaPagCompra;
    private javax.swing.JComboBox<String> jComboBoxSexoCompra;
    private javax.swing.JComboBox<Object> jComboBoxVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCompra;
    private javax.swing.JTextArea jTextAreaDescricaoCompra;
    private javax.swing.JTextArea jTextAreaObservacaoCompra;
    private javax.swing.JTextField jTextFieldDataCompra;
    private javax.swing.JTextField jTextFieldNascimentoCompra;
    private javax.swing.JTextField jTextFieldPesoCompra;
    private javax.swing.JTextField jTextFieldPrazoCompra;
    private javax.swing.JTextField jTextFieldRacaCompra;
    private javax.swing.JTextField jTextFieldValorCompra;
    private javax.swing.JTextField jTextFieldVendedor;
    // End of variables declaration//GEN-END:variables
}
